local blips = {
	{
		type = "Coffee shop", -- Type of location, best to keep this consistent with others of the same type.
		id = 76,  -- Blip ID to display (https://docs.fivem.net/docs/game-references/blips/)
		-- Coordinates
		x = -1281.38, 
		y = -1129.33, 
		z = 6.91, 
		name = "Bean Machine", -- Name of location. For a simple blip, you can remove this line and every line until phone.
		image = "beanmachine_vespucci",  -- Name of 256x128 image in mapimages.ytd to use 
		address = "1/8106 Magellan Ave, Vespucci, SA", -- Address of location
		description = "Rainier-based coffeehouse chain known for its signature roasts, light bites and WiFi availability.", -- Description of location. Leave empty to igmore.
		lowpriority = true, -- Setting this to false will make it appear on the minimap at all times, even if it's not visible there.
		--[[ THIS SECTION IS A WORK IN PROGRESS AND DOESN'T WORK!
			Check1 = { Title = "Dine-in", Value = 79, },
			Check2 = { Title = "Drive-through", Value = 80, },
			Check3 = { Title = "Delivery", Value = 79, },
		]]
		website = "beanmachinecoffee.com", -- Optional
		--phone = "+1 310-555-0134", -- Optional
	},
	{
		type = "Coffee shop",
		id = 76,
		x = -477.11, 
		y = 1116.29, 
		z = 320.23, 
		name = "Bean Machine",
		image = "beanmachine_galileo",
		address = "5020 E Galileo Ave, Galileo Park, SA",
		description = "Rainier-based coffeehouse chain known for its signature roasts, light bites and WiFi availability.",
		lowpriority = true,
		website = "beanmachinecoffee.com",
	},
	{
		type = "Coffee shop",
		id = 76,
		x = -319.99, 
		y = -818.64, 
		z = 32.47, 
		name = "Bean Machine",
		image = "beanmachine_dtls",
		address = "8069 Vespucci Blvd, Los Santos, SA",
		description = "Rainier-based coffeehouse chain known for its signature roasts, light bites and WiFi availability.",
		lowpriority = true,
		website = "beanmachinecoffee.com",
	},
	{
		type = "Coffee shop",
		id = 76,
		x = -1364.87, 
		y = -207.35, 
		z = 44.68, 
		name = "Bean Machine",
		image = "beanmachine_rockfordmorningwood",
		address = "7162 Morningwood Blvd, Rockford Hills, SA",
		description = "Rainier-based coffeehouse chain known for its signature roasts, light bites and WiFi availability.",
		lowpriority = true,
		website = "beanmachinecoffee.com",
	},
	{
		type = "Coffee shop",
		id = 76,
		x = -849.97, 
		y = -358.25, 
		z = 38.68, 
		name = "Bean Machine",
		image = "beanmachine_rockfordheritage",
		address = "7226 Heritage Way, Rockford Hills, SA",
		description = "Rainier-based coffeehouse chain known for its signature roasts, light bites and WiFi availability.",
		lowpriority = true,
		website = "beanmachinecoffee.com",
	},
	{
		type = "Coffee shop",
		id = 76,
		x = -687.87, 
		y = 318.04, 
		z = 83.09, 
		name = "Bean Machine",
		image = "beanmachine_eclipsemedical",
		address = "1/6186 S Mo Milton Dr, West Vinewood, SA",
		description = "Rainier-based coffeehouse chain known for its signature roasts, light bites and WiFi availability.",
		lowpriority = true,
		website = "beanmachinecoffee.com",
	},
	{
		type = "Office",
		id = 475,
		x = -496.87, 
		y = -2910.28, 
		z = 6, 
		name = "Post Op Depository",
		image = "postop_port",
		address = "10040 Plaice Pl, Los Santos, SA",
		lowpriority = true,
	},
	{
		type = "Office",
		id = 475,
		x = 904.76, 
		y = -159.54, 
		z = 74.17, 
		name = "Downtown Cab Co",
		image = "downtown_cab_co",
		address = "7295 Tangerine Street, Los Santos, SA",
		lowpriority = true,
		phone = "(323) 555-5555"
	},
	{
		type = "Office",
		id = 475,
		x = 292.44, 
		y = 351.66, 
		z = 105.37, 
		name = "PolicingMP Management Center",
		image = "policingmp",
		address = "7092 Clinton Avenue, Los Santos, SA",
		lowpriority = true,
		website = "www.policingmp.net"
	},
	{
		type = "Power station",
		id = 1,
		x = 2734.19, 
		y = 1490.13, 
		z = 30.78, 
		name = "Palmer-Taylor Power Station",
		address = "3062-3063 Senora Way, Los Santos County SA",
		lowpriority = true,
	},
	{
		type = "Car dealership",
		id = 326,
		x = -48.21, 
		y = -1107.03, 
		z = 26.44, 
		name = "Premium Deluxe Motorsport",
		image = "pdm",
		address = "8167 Power St, Los Santos, SA",
		description = "Best of the best cars and completely reasonable interest rates.",
		lowpriority = true,
	},
	{
		type = "Car rentals",
		id = 326,
		x = -836.18, 
		y = -2348.95, 
		z = 14.69, 
		name = "Touchdown Car Rentals",
		image = "touchdown",
		address = "10008 Greenwich Parkway, Los Santos, SA",
		description = "A fair selection of cars from $4 PPPD.",
		lowpriority = true,
	},
	{
		type = "Coffee shop",
		id = 76,
		x = 281.6, 
		y = -966.78, 
		z = 29.42, 
		name = "Bean Machine",
		image = "beanmachine_legion",
		address = "8051 Atlee St, Los Santos, SA",
		description = "Rainier-based coffeehouse chain known for its signature roasts, light bites and WiFi availability.",
		lowpriority = true,
		website = "beanmachinecoffee.com",
	},
	{
		type = "Coffee shop",
		id = 76,
		x = 464.62, 
		y = -717.56, 
		z = 27.53, 
		name = "Bean Machine",
		image = "beanmachine_simmet",
		address = "8044 Simmet Alley, Los Santos, SA",
		description = "Rainier-based coffeehouse chain known for its signature roasts, light bites and WiFi availability.",
		lowpriority = true,
		website = "beanmachinecoffee.com",
	},
	{
		type = "Office",
		id = 475,
		x = 1237.89, 
		y = -3257.14, 
		z = 7.15, 
		name = "Alpha Mail Distribution Center",
		address = "10108 Terminal, Port of Los Santos, SA",
		lowpriority = true,
	},
	{
		type = "Police department",
		id = 60,
        x = 442.18,
        y = -983.14,
        z = 30.10,
		name = "Mission Row Community Police Station",
		image = "lspd_mission",
		address = "8047 Sinner St, Los Santos, SA",
		lowpriority = true,
		website = "lspdonline.org",
	},
	{
		type = "Police department",
		id = 60,
        x = -1627.06,
        y = -1024.31,
        z = 13.15,
		name = "Del Perro Police Department Pier Substation",
		image = "dppd_pier",
		address = "8047 Sinner St, Los Santos, SA",
		lowpriority = true,
	},
	{
		type = "Police department",
		id = 60,
        x = 456.14,
        y = -1094.54,
        z = 29.4,
		name = "Mission Row Official Police Garage",
		image = "lspd_mission_garage",
		address = "8178-8179 Adam's Apple Boulevard, Los Santos, SA",
		lowpriority = true,
	},
	{
		type = "Police department",
		id = 60,
        x = -589.27,
        y = -922.5,
        z = 24.03,
		name = "Olympic Community Police Station",
		image = "lspd_olympic",
		address = "8144 Palomino Ave, Los Santos, SA",
		lowpriority = true,
		website = "lspdonline.org",
	},
	{
		type = "Police department",
		id = 60,
        x = -1094.83,
        y = -836.18,
        z = 38.06,
		name = "Del Perro Police Department",
		address = "8090 San Andreas Ave, Del Perro, SA",
		lowpriority = true,
		website = "delperropd.org",
	},
	{
		type = "Police department",
		id = 60,
        x = -561.55,
        y = -132.2,
        z = 38.21,
		name = "Rockford Hills Police Department",
		address = "7229 Eastbourne Way, Rockford Hills, SA",
		image = "rhpd_hq",
		lowpriority = true,
	},
	{
		type = "Police department",
		id = 60,
        x = 832.88,
        y = -1290.04,
        z = 28.23,
		name = "San Andreas Highway Patrol Southern Division",
		image = "sahp_lamesa",
		address = "9246 Popular St, Los Santos, SA",
		lowpriority = true,
		website = "sahp.sa.gov",
	},
	{
		type = "Police department",
		id = 60,
        x = 1849.66,
        y = 3690.9,
        z = 34.26,
		name = "Majestic County Sheriff's Office",
		image = "mcso_sandy",
		address = "3004 Alhambra Drive, Sandy Shores, SA",
		lowpriority = true,
	},
	{
		type = "Police department",
		id = 60,
        x = 374.32,
        y = -1606.48,
        z = 29.29,
		name = "Davis Sheriff's Station",
		image = "lssd_davis",
		address = "9148 Innocence Boulevard, Davis, SA",
		lowpriority = true,
	},
	{
		type = "Theater",
		id = 86,
		x = -153.89, 
		y = -1083.32, 
		z = 27.16, 
		name = "Facade Theater",
		image = "facadetheater",
		address = "8161 Power St, Los Santos, SA",
		description = "Midsize live music venue & site of major awards shows with classy decor, luxury boxes & bars.",
		lowpriority = true,
	},
	{
		type = "Coffee shop",
		id = 76,
		x = -142.27,  
		y = -1022.1, 
		z = 27.98, 
		name = "The Camel Toe",
		image = "cameltoe",
		address = "Shop 1 8163 Vespucci Blvd, Los Santos, SA",
		lowpriority = true,
	},
	{
		type = "Hotel",
		id = 84,
		x = -137.68, 
		y = -989.01, 
		z = 29.37, 
		name = "The Mile High Club",
		image = "mhc",
		address = "8157-8164 Vespucci Boulevard, Los Santos, SA",
		description = "Within the L.S. LIVE entertainment complex, this 5-star hotel features free Wi-Fi and flat-screens, as well as marble bathrooms and 400-thread-count linens. Classy suites add sitting areas; upgraded suites have separate bedrooms. Club rooms offer access to a lounge with free food and drinks. Room service is offered 24/7. Amenities include a sophisticated regional restaurant, a cafe and 2 bars. There's also a luxe spa, a rooftop outdoor pool and hot tub, plus a fitness center.",
		lowpriority = true,
	},
	{
		type = "Tram stop",
		id = 85,
		x = -213.58, 
		y = -1033.19, 
		z = 30.15, 
		name = "Pillbox South",
		image = "lst_pillboxs",
		address = "8159 Alta St, Los Santos, SA",
		lowpriority = true,
	},
	{
		type = "Adult entertainment club",
		id = 121,
		x = 126.55, 
		y = -1289.25, 
		z = 29.28, 
		name = "Vanilla Unicorn Gentleman's Club",
		image = "vanillaunicorn",
		address = "9047 Elgin Ave, Los Santos, SA",
		lowpriority = true,
	},
	{
		type = "Coffee shop",
		id = 76,
		x = -1232.51,  
		y = -1179.7, 
		z = 7.66, 
		name = "Calm Coffee",
		image = "calmcoffee",
		address = "8216 Cortes St, Los Santos, SA",
		lowpriority = true,
	},
	{
		type = "Train Station",
		id = 85,
		x = 506.17,  
		y = -1460.04, 
		z = 29.62, 
		name = "Market Station",
		image = "markettrainstation",
		address = "9060 Capital Blvd, Los Santos, SA",
		lowpriority = true,
	},
	{
		type = "Fast food restaurant",
		id = 88,
		x = -1191.24, 
		y = -889.72, 
		z = 14, 
		name = "Burger Shot",
		image = "bs_vespucci",
		address = "8092 San Andreas Ave, Del Perro, SA",
		description = "Well-known fast-food chain serving grilled burgers, fries & shakes.",
		lowpriority = true,
		website = "burgershot.net",
	},
	{
		type = "Fast food restaurant",
		id = 88,
		x = 85.35, 
		y = 287.26, 
		z = 111.2, 
		name = "Up-N-Atom Burger",
		image = "upnatom_vinewood",
		address = "7086 Vinewood Boulevard, Los Santos, SA",
		description = "Classic San Andreas-based burger chain serving customizable patties, hand-cut fries and thick shakes.",
		lowpriority = true,
	},
	{
		type = "Chicken restaurant",
		id = 88,
		x = -141.59, 
		y = -262.3, 
		z = 43.6, 
		name = "Cluckin' Bell",
		image = "cb_rockford",
		address = "7245 Las Lagunas Blvd, Rockford Hills, SA",
		description = "Restaurant chain known for its buckets of fried chicken, plus wings & sides.",
		lowpriority = true,
		website = "CluckinBellHappyChicken.com",
	},
	{
		type = "Chicken restaurant",
		id = 88,
		x = 139.39, 
		y = -1467.03, 
		z = 29.36, 
		name = "Lucky Plucker",
		image = "luckyplucker_strawberry",
		address = "9142 Strawberry Avenue, Strawberry, SA",
		lowpriority = true,
	},
	{
		type = "Store",
		id = 52,
		x = -87.17, 
		y = 6409.73, 
		z = 31.65, 
		name = "Xero",
		image = "xero_paleto",
		address = "1054 Paleto Blvd, Paleto Bay, SA",
		lowpriority = true,
	},
	{
		type = "Store",
		id = 52,
		x = -675.94, 
		y = 5836.9, 
		z = 17.33, 
		name = "Bayview Lodge General Store",
		image = "bayview_store",
		address = "1079 Procopio Promenade, Paleto Bay, SA",
		lowpriority = true,
	},
	{
		type = "Store",
		id = 52,
		x = -533.06, 
		y = -1225.05, 
		z = 18.44, 
		name = "Xero 24",
		image = "xero_seoul",
		address = "8254 Calais Avenue, Los Santos, SA",
		lowpriority = true,
	},
	{
		type = "Store",
		id = 52,
		x = 293.26, 
		y = -1267.22, 
		z = 29.45, 
		name = "Xero 24",
		image = "xero24_strawberry",
		address = "9051 Strawberry Avenue, Los Santos, SA",
		lowpriority = true,
	},
	{
		type = "Store",
		id = 52,
		x = -2068.78, 
		y = -327.32, 
		z = 13.32, 
		name = "Xero",
		image = "xero24_delperro",
		address = "7001 Great Ocean Highway, Del Perro, SA",
		lowpriority = true,
	},
	{
		type = "Store",
		id = 52,
		x = 388.56, 
		y = -829.08, 
		z = 29.31, 
		name = "Digital Den",
		image = "digitalden_mission",
		address = "8043 San Andreas Avenue, Los Santos, SA",
		description = "Chain retailer with an array of brand-name electronics, computers, appliances & more.",
		lowpriority = true,
	},
	{
		type = "Store",
		id = 52,
		x = 424.31, 
		y = -805.93, 
		z = 29.49, 
		name = "Binco",
		image = "binco_mission",
		address = "8045 Sinner Street, Los Santos, SA",
		description = "Street clothing store.",
		lowpriority = true,
	},
	{
		type = "Motel",
		id = 84,
		x = 379.01, 
		y = -1802.93, 
		z = 29.09, 
		name = "Rancho Motel",
		image = "davis_motel1",
		address = "9157 Roy Lowenstein Boulevard, Davis, SA",
		description = "Motel with clean rooms and servicable facilities. Perfect for train lovers and gun crime enthusiasts.",
		lowpriority = true,
	},
	{
		type = "Motel",
		id = 84,
		x = -689.38, 
		y = 5762.86, 
		z = 17.33, 
		name = "Bayview Lodge",
		image = "bayview_motel",
		address = "1079 Procopio Promenade, Paleto Bay, SA",
		lowpriority = true,
	},
	{
		type = "Store",
		id = 52,
		x = 381.77, 
		y = -1782.88, 
		z = 29.52, 
		name = "Rancho Discount Grocery",
		image = "davis_store1",
		address = "9157 Roy Lowenstein Boulevard, Davis, SA",
		description = "Local grocery store with a wide selection of alcohol and a distinct lack of fresh produce.",
		lowpriority = true,
	},
	{
		type = "Store",
		id = 52,
		x = 157.95, 
		y = 6650.12, 
		z = 31.67, 
		name = "Pat's Keys",
		address = "1012 Route 1, Paleto Bay, SA",
		description = "Keycutter and locksmith.",
		image = "pats_keys",
		lowpriority = true,
	},
	{
		type = "Store",
		id = 52,
		x = 164.47, 
		y = 6639.25, 
		z = 31.61, 
		name = "Don's Country Store",
		address = "1012 Route 1, Paleto Bay, SA",
		image = "dons_country_store",
		description = "24/7 chain store disguised as a local business.",
		lowpriority = true,
	},
	{
		type = "Motel",
		id = 84,
		x = -92.11, 
		y = 6335.95, 
		z = 31.49, 
		name = "Dreamview Motel",
		image = "dreamview_motel1",
		address = "1024 Great Ocean Hwy, Paleto Bay, SA",
		description = "Multi-floor motel with spacious rooms, private kitchen facilities and flatscreen TVs.",
		lowpriority = true,
	},
	{
		type = "Motel",
		id = 84,
		x = 324.27, 
		y = -213.29, 
		z = 54.09, 
		name = "Pink Cage Motel",
		image = "pinkcage_motel",
		address = "7109 Roy Hawick Avenue, Los Santos, SA",
		description = "Recently modernized three-star motel featuring spacious and tidy rooms with bathrooms, flatscreen TVs and a shared swimming pool.",
		lowpriority = true,
	},
	{
		type = "Hotel",
		id = 84,
		x = 281.92, 
		y = -1078.48, 
		z = 29.4, 
		name = "Templar Hotel",
		image = "mission_motel",
		address = "8174 Fantastic Place, Los Santos, SA",
		description = "One-star highrise hotel with small, functional rooms.",
		lowpriority = true,
	},
	{
		type = "Bar",
		id = 93,
		x = 1654.87, 
		y = 4850.85, 
		z = 42.01, 
		name = "The Black Lantern",
		image = "blacklantern_grapeseed",
		address = "2007 Grapeseed Main Street, Grapeseed, SA",
		lowpriority = true,
	},
	{
		type = "Restaurant",
		id = 88,
		x = -1340.03, 
		y = -1079.5, 
		z = 6.94, 
		name = "Venetian",
		image = "drusillas_vespucci",
		address = "8102 Conquistador Street, Rockford Hills, SA",
		description = "Four-star Italian restaurant located by Vespucci Beach.",
		lowpriority = true,
	},
	{
		type = "Restaurant",
		id = 88,
		x = -688.75, 
		y = 5800.0, 
		z = 17.33, 
		name = "Bayview Lodge Diner",
		image = "bayview_lodge",
		address = "1079 Procopio Promenade, Paleto Bay, SA",
		lowpriority = true,
	},
	{
		type = "Bar",
		id = 93,
		x = 1223.44, 
		y = -417.14, 
		z = 67.78, 
		name = "Mirror Park Tavern",
		image = "mirrorpark_tavern",
		address = "7345 Mirror Park Boulevard, Los Santos, SA",
		lowpriority = true,
	},
	{
		type = "Open Home",
		id = 40,
		x = 1223.84, 
		y = -670.26, 
		z = 63.5, 
		name = "Open Home",
		address = "7333 Mirror Park Boulevard, Los Santos, SA",
		description = "A residential address for anyone to use as part of their roleplay. First come, first serve.",
		lowpriority = true,
	},
	{
		type = "Open Home",
		id = 40,
		x = 940.44, 
		y = -653.22, 
		z = 58.44, 
		name = "Open Home",
		address = "7320 West Mirror Drive, Los Santos, SA",
		description = "A residential address for anyone to use as part of their roleplay. First come, first serve.",
		lowpriority = true,
	},
	{
		type = "Open Home",
		id = 40,
		x = 945.28, 
		y = -521.99, 
		z = 60.63, 
		name = "Open Home",
		address = "7310 West Mirror Drive, Los Santos, SA",
		description = "A residential address for anyone to use as part of their roleplay. First come, first serve.",
		lowpriority = true,
	},
	{
		type = "Open Home",
		id = 40,
		x = -108.77, 
		y = -8.1, 
		z = 70.52, 
		name = "Open Home",
		address = "7138 Las Lagunas Boulevard, West Vinewood, SA",
		description = "A residential address for anyone to use as part of their roleplay. First come, first serve.",
		lowpriority = true,
	},
	{
		type = "Open Home",
		id = 40,
		x = -4.05, 
		y = 527.32, 
		z = 175, 
		name = "Open Home",
		address = "3671/6085 Whispymound Drive, Los Santos, SA",
		description = "A residential address for anyone to use as part of their roleplay. First come, first serve.",
		lowpriority = true,
	},
	{
		type = "Open Home",
		id = 40,
		x = -804.78, 
		y = 176.25, 
		z = 72.84, 
		name = "Open Home",
		address = "7063 Portola Drive, Rockford Hills, SA",
		description = "A residential address for anyone to use as part of their roleplay. First come, first serve.",
		lowpriority = true,
	},
	{
		type = "Open Home",
		id = 40,
		x = -1154.31, 
		y = -1518.03, 
		z = 10.63, 
		name = "Open Home",
		address = "8209 Goma Street, Los Santos, SA",
		description = "A residential address for anyone to use as part of their roleplay. First come, first serve.",
		lowpriority = true,
	},
	{
		type = "Open Home",
		id = 40,
		x = -14.53, 
		y = -1434.09, 
		z = 31.12, 
		name = "Open Home",
		address = "9075 Forum Drive, Los Santos, SA",
		description = "A residential address for anyone to use as part of their roleplay. First come, first serve.",
		lowpriority = true,
	},
	{
		type = "Open Home",
		id = 40,
		x = 1973.94, 
		y = 3818.93, 
		z = 33.44, 
		name = "Open Home",
		address = "3009 Zancudo Avenue, Sandy Shores, SA",
		description = "A residential address for anyone to use as part of their roleplay. First come, first serve.",
		lowpriority = true,
	},
	{
		type = "Open Home",
		id = 40,
		x = 2448.94, 
		y = 4977.77, 
		z = 46.81, 
		name = "Open Home",
		address = "2027 Grapeseed Avenue, Grapeseed, SA",
		description = "A residential address for anyone to use as part of their roleplay. First come, first serve.",
		lowpriority = true,
	},
	{
		type = "Open Home",
		id = 40,
		x = 19.72, 
		y = -1441.02, 
		z = 30.96,
		name = "Open Home",
		address = "9075 Forum Drive, Los Santos, SA",
		description = "A residential address for anyone to use as part of their roleplay. First come, first serve.",
		lowpriority = true,
	},
	{
		type = "Open Home",
		id = 40,
		x = 472.02, 
		y = 2601.92, 
		z = 44.47,
		name = "Open Home",
		address = "4018 Route 68, Harmony, SA",
		description = "A residential address for anyone to use as part of their roleplay. First come, first serve.",
		lowpriority = true,
	},
	{
		type = "Open Home",
		id = 40,
		x = 1271.78, 
		y = -1712.35, 
		z = 54.77, 
		name = "Open Home",
		address = "9340 Amarillo Vista, East Los Santos, SA",
		description = "A residential address for anyone to use as part of their roleplay. First come, first serve.",
		lowpriority = true,
	},
	{
		type = "Open Home",
		id = 40,
		x = 1298.33, 
		y = -1746.84, 
		z = 54.28, 
		name = "Open Home",
		address = "9342 Amarillo Vista, East Los Santos, SA",
		description = "A residential address for anyone to use as part of their roleplay. First come, first serve.",
		lowpriority = true,
	},
	{
		type = "Open Home",
		id = 40,
		x = -1096.47, 
		y = -1668.61, 
		z = 8.41, 
		name = "Open Home",
		address = "8207 Vespucci Promenade, Los Santos, SA",
		description = "A residential address for anyone to use as part of their roleplay. First come, first serve.",
		lowpriority = true,
	},
	{
		type = "Open Home",
		id = 40,
		x = -1985.47, 
		y = -502.47, 
		z = 12.18, 
		name = "Open Home",
		address = "7006 Great Ocean Highway, Del Perro, SA",
		description = "A residential address for anyone to use as part of their roleplay. First come, first serve.",
		lowpriority = true,
	},
	{
		type = "Open Home",
		id = 40,
		x = -1565.29, 
		y = -391.25, 
		z = 59.15, 
		name = "Open Home",
		address = "7028 Prosperity Street, Del Perro, SA",
		description = "A residential apartment complex for anyone to use as part of their roleplay. First come, first serve.",
		lowpriority = true,
	},
	{
		type = "Open Home",
		id = 40,
		x = -40.58, 
		y = 6576.91, 
		z = 31.45, 
		name = "Open Home",
		address = "1057 Procopio Drive, Paleto Bay, SA",
		description = "A residential address for anyone to use as part of their roleplay. First come, first serve.",
		lowpriority = true,
	},
	{
		type = "Open Home",
		id = 40,
		x = -443.07, 
		y = 6265.79, 
		z = 29.8, 
		name = "Open Home",
		address = "1075 Procopio Drive, Paleto Bay, SA",
		description = "A residential address for anyone to use as part of their roleplay. First come, first serve.",
		lowpriority = true,
	},
}


-- Create map blips

Citizen.CreateThread(function()
    RequestStreamedTextureDict("mapimages") -- Load mapimages.ytd into memory
    for _, item in pairs(blips) do
        item.blip = AddBlipForCoord(item.x, item.y, item.z)
        SetBlipSprite(item.blip, item.id)
        SetBlipAsShortRange(item.blip, item.lowpriority)
        BeginTextCommandSetBlipName("STRING")
        AddTextComponentString(item.type)
        EndTextCommandSetBlipName(item.blip)
        if item.name then
            if item.image then
                exports['blip_info']:SetBlipInfoImage(item.blip, "mapimages", item.image)
            end
            exports['blip_info']:SetBlipInfoTitle(item.blip, item.name, false)
            exports['blip_info']:AddBlipInfoHeader(item.blip, item.address, "")
            exports['blip_info']:AddBlipInfoText(item.blip, item.type)
            if item.description then
                exports['blip_info']:AddBlipInfoText(item.blip, item.description)
            end
            --[[ THIS SECTION IS A WORK IN PROGRESS AND DOESN'T WORK!
                if item.Check1.Title then
                exports['blip_info']:AddBlipInfoIcon(blip, "", item.Check1.Title, item.Check1.Value, 0, false)
                if item.Check2.Title then
                    exports['blip_info']:AddBlipInfoIcon(blip, "", item.Check2.Title, item.Check2.Value, 0, false)
                    if item.Check3.Title then
                        exports['blip_info']:AddBlipInfoIcon(blip, "", item.Check3.Title, item.Check3.Value, 0, false)
                    end
                end
            end
            ]]
            if item.website then
                exports['blip_info']:AddBlipInfoText(item.blip, item.website)
            end
            if item.phone then
                exports['blip_info']:AddBlipInfoText(item.blip, item.phone)
            end
        end
        Citizen.Wait(0)
    end
end)